---
- name: Install pupet server
  hosts: all
  remote_user: ubuntu
  become: yes

  roles:
    - basic_setup

  tasks:
  - name: add pupet repository
    ansible.builtin.get_url:
      url: https://apt.puppet.com/puppet8-release-bionic.deb
      dest: /tmp/puppet-release-bionic.deb

  - name: Install Puppet repository package
    ansible.builtin.apt:
      deb: /tmp/puppet-release-bionic.deb
  
  - name: apt update
    ansible.builtin.apt:
      update_cache: yes
    
  - name: Allow incoming TCP traffic on port 8140 (Puppet)
    ansible.builtin.iptables:
      chain: INPUT
      protocol: tcp
      destination_port: 8140
      jump: ACCEPT
      state: present

  - name: Save iptables rules (on Ubuntu)
    ansible.builtin.command: iptables-save
    register: iptables_rules

  - name: Install puppetserver package
    ansible.builtin.apt:
      name: puppetserver
      state: present

  - name: Copy puppetserver config directory
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/../configs/puppetserver_config/puppetserver/"
      dest: /etc/puppetlabs/puppetserver/
      owner: root
      group: root
      mode: '0644'
      recurse: yes

  - name: Enable Puppet Server service
    ansible.builtin.systemd:
      name: puppetserver
      enabled: yes
      state: started

  - name: Reboot the server
    ansible.builtin.reboot: