version: '3'
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: always

  apache:
    image: slime3000fly/apache_website:latest
    ports:
      - "80:80"
    restart: always

  prometheus:
    image: prom/prometheus
    ports: 
      - "9090:9090"
    volumes:
      - /etc/prometheus.yml

  apache_exporter:
    image: prom/apache-exporter
    ports:
      - "9117:9117"
    environment:
      - STATUSURL=http://apache:80/server-status?auto
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
