Vagrant.require_version ">= 2.4.0"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  config.vm.provider :virtualbox do |vb|
    vb.name = "DevOps"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.ask_vault_pass  = true
    ansible.playbook = "main.yml"
  end
end
