---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
  app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: backend
  template:
    metadata:
      labels:
        service: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/slime3000fly/backend:latest
      ports:
      - containerPort: 5000