# widget:
#   type: pihole
#   url: http://172.19.0.2
#   version: 5 # required if running v6 or higher, defaults to 5
#     #key: yourpiholeapikey # optional, in v6 can be your password or app password
