---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: duckduckgo
    target: _blank

# - docker:
#    - name: my-docker
#      type: docker
#      socket: /var/run/docker.sock
