[windows]
win1 ansible_host=192.168.1.186

[windows:vars]
ansible_connection=ssh
ansible_user=sshadmin
ansible_password=USE_EXTRA_VARS
ansible_remote_tmp=C:\Windows\Temp\ansible
ansible_shell_type=powershell
ansible_shell_executable=pwsh
