[windows]
win1 ansible_host=192.168.1.186

[windows:vars]
ansible_connection=winrm
ansible_winrm_transport=basic
ansible_winrm_server_cert_validation=ignore
ansible_port=5985
ansible_user=sshadmin
ansible_password=USE_EXTRA_VARS
