---
- name: Install Puppet Agent 8 on Windows via WinRM
  hosts: windows
  gather_facts: no
  become_method: enable
  vars:
    puppet_agent_url: "https://downloads.puppet.com/windows/puppet8/puppet-agent-x64-latest.msi"
    ### -------------------------------------------------------------------------------------------------------------
    puppet_server_ip: "141.147.49.65"  # !!!!!CHANGE!!!!!
    ### -------------------------------------------------------------------------------------------------------------

  tasks:
    # - name: Download Puppet Agent MSI
    #   win_get_url:
    #     url: "{{ puppet_agent_url }}"
    #     dest: C:\puppet-agent.msi

    # - name: Install Puppet Agent
    #   win_package:
    #     path: C:\puppet-agent.msi
    #     state: present
    #     arguments: /qn
    # - name: Usuń pierwszą linię, jeśli jest dokładnie "pierwsza linia"
    #   win_lineinfile:
    #     path: C:\ProgramData\PuppetLabs\puppet\etc\puppet.conf
    #     regexp: '^ser'
    #     state: absent
  
    
    - name: Zmień server=example na server=131
      win_lineinfile:
        path: C:\ProgramData\PuppetLabs\puppet\etc\puppet.conf
        regexp: '^ser'
        line: 'server={{ puppet_server_ip }}'
        backup: yes

    - name: Run puppet agent to request certificate
      win_command: '"C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" agent --test'
      register: puppet_output
      ignore_errors: yes

    - name: Print puppet output
      debug:
        var: puppet_output.stdout_lines
