apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '5000'
spec:
  selector:
    app: movie
    tier: backend
  type: NodePort
  ports:
    - name: port-5000
      protocol: TCP
      port: 5000
      targetPort: 5000

