apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: movie
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
