apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: ghcr.io/slime3000fly/mongodb:latest 
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: admin  
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: admin  
      volumes:
      - name: mongodb-data
        emptyDir: {}
