apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: movie
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie
      tier: backend 
  template:
    metadata:
      labels:
        app: movie
        tier: backend 
    spec:
      containers:
      - name: backend
        image: ghcr.io/slime3000fly/backend:prometheus
        env:
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-credentials
                key: password
        ports:
        - containerPort: 5000
