name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
     IMAGE_NAME: 'apache_website' # variable to store docker image name

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Change directory
        run: cd GoogleCloud

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME -f GoogleCloud/infra/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:latest
